name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  # Build job
  build:
    concurrency: ci-${{ github.ref }}
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        env: 
          CI: false
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
    
